// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaClinicalSuite.Data;

#nullable disable

namespace PharmaClinicalSuite.Migrations
{
    [DbContext(typeof(PharmaClinicalSuiteContext))]
    partial class PharmaClinicalSuiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.AdverseEvents", b =>
                {
                    b.Property<int>("AdverseEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdverseEventId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.HasKey("AdverseEventId")
                        .HasName("PK__AdverseE__9AA4ACB0F54C4ED7");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TrialId");

                    b.ToTable("AdverseEvents");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.AuditTrail", b =>
                {
                    b.Property<int>("AuditTrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditTrailId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditTrailId")
                        .HasName("PK__AuditTra__41B2DDB36F2CE413");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+CaseReportform", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.HasKey("FormId")
                        .HasName("PK__CaseRepo__FB05B7BD5C1893E6");

                    b.HasIndex("TrialId");

                    b.ToTable("CaseReportforms");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+DataCollectionFields", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("FormsFormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("FieldId")
                        .HasName("PK__DataColl__C8B6FF273546AC0B");

                    b.HasIndex("FormsFormId");

                    b.ToTable("DataCollectionFields");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFieldData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"));

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataId")
                        .HasName("PK__Particip__9D05305D2A166DB6");

                    b.HasIndex("EntryId");

                    b.HasIndex("FieldId");

                    b.ToTable("ParticipantFieldData");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFormEntries", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("CaseReportformsFormId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.HasKey("EntryId")
                        .HasName("PK__Particip__F57BD2D7C4C40332");

                    b.HasIndex("CaseReportformsFormId");

                    b.ToTable("ParticipantFormEntries");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WithDrawalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WithDrawalReasonId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F6877FBF7A96B3D");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TrialId");

                    b.HasIndex("WithDrawalReasonId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Investigator", b =>
                {
                    b.Property<int>("InvestigatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestigatorId"));

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigatorId")
                        .HasName("PK__Investig__A09546DB837CFE7F");

                    b.ToTable("Investigator");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Participants", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nchar")
                        .IsFixedLength();

                    b.Property<string>("GuardianInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParticipantId")
                        .HasName("PK__Particip__7227997E3187744A");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Sites", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId")
                        .HasName("PK__Sites__B9DCB903D6784133");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialInvestigator", b =>
                {
                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.Property<int>("InvestigatorId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrialId", "InvestigatorId")
                        .HasName("PK__TrialInv__451971C9ECD67464");

                    b.HasIndex("InvestigatorId");

                    b.ToTable("TrialsInvestigators");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialSite", b =>
                {
                    b.Property<int>("TrialSiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrialSiteId"));

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.Property<int>("TrialTypeId")
                        .HasColumnType("int");

                    b.HasKey("TrialSiteId");

                    b.HasIndex("TrialId");

                    b.ToTable("TrialSite");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialType", b =>
                {
                    b.Property<int>("TrialTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrialTypeId"));

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrialTypeId")
                        .HasName("PK__TrialTyp__59CAB3A78A1EBCDE");

                    b.ToTable("TrialTypes");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Trials", b =>
                {
                    b.Property<int>("TrialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrialId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TrialTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrialId")
                        .HasName("PK__Trials__EF1025A4C7A82768");

                    b.HasIndex("TrialTypeId");

                    b.ToTable("Trials");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Visit");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.WithdrawalReason", b =>
                {
                    b.Property<int>("WithdrawalReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WithdrawalReasonID"));

                    b.Property<string>("WithdrawalReasonDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WithdrawalReasonID")
                        .HasName("PK__Withdraw__BE8C1525ACA37278");

                    b.ToTable("WithdrawalReasons");
                });

            modelBuilder.Entity("TrialSite", b =>
                {
                    b.Property<int>("TrialId")
                        .HasColumnType("int")
                        .HasColumnName("TrialID");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteID");

                    b.HasKey("TrialId", "SiteId")
                        .HasName("PK__TrialSit__C48DEE34904186B5");

                    b.HasIndex("SiteId");

                    b.ToTable("TrialSites", (string)null);
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.AdverseEvents", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Participants", "Participants")
                        .WithMany("AdverseEvents")
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("FK__AdverseEv__Parti__4BAC3F29");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", "Trials")
                        .WithMany("AdverseEvents")
                        .HasForeignKey("TrialId")
                        .IsRequired()
                        .HasConstraintName("FK__AdverseEv__Trial__4CA06362");

                    b.Navigation("Participants");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+CaseReportform", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", "Trials")
                        .WithMany("CaseReportForms")
                        .HasForeignKey("TrialId")
                        .IsRequired()
                        .HasConstraintName("FK__CaseRepor__Trial__5BE2A6F2");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+DataCollectionFields", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Data_Collection+CaseReportform", "Forms")
                        .WithMany("DataCollectionFields")
                        .HasForeignKey("FormsFormId")
                        .IsRequired()
                        .HasConstraintName("FK__DataColle__FormI__60A75C0F");

                    b.Navigation("Forms");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFieldData", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFormEntries", "ParticipantFormEntries")
                        .WithMany("ParticipantFieldData")
                        .HasForeignKey("EntryId")
                        .IsRequired()
                        .HasConstraintName("FK__Participa__Entry__68487DD7");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.Data_Collection+DataCollectionFields", "DataCollectionFields")
                        .WithMany("ParticipantFieldData")
                        .HasForeignKey("FieldId")
                        .IsRequired()
                        .HasConstraintName("FK__Participa__Field__693CA210");

                    b.Navigation("DataCollectionFields");

                    b.Navigation("ParticipantFormEntries");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFormEntries", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Data_Collection+CaseReportform", "CaseReportforms")
                        .WithMany("ParticipantFormEntries")
                        .HasForeignKey("CaseReportformsFormId")
                        .IsRequired()
                        .HasConstraintName("FK__Participa__FormI__656C112C");

                    b.Navigation("CaseReportforms");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Enrollment", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Participants", "Participants")
                        .WithMany("Enrollments")
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Parti__45F365D3");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", "Trials")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrialId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Trial__46E78A0C");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.WithdrawalReason", "WithdrawalReasons")
                        .WithMany("Enrollments")
                        .HasForeignKey("WithDrawalReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Withd__47DBAE45");

                    b.Navigation("Participants");

                    b.Navigation("Trials");

                    b.Navigation("WithdrawalReasons");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialInvestigator", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Investigator", "Investigator")
                        .WithMany("TrialsInvestigators")
                        .HasForeignKey("InvestigatorId")
                        .IsRequired()
                        .HasConstraintName("FK__TrialInve__Inves__52593CB8");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", "Trials")
                        .WithMany("TrialsInvestigators")
                        .HasForeignKey("TrialId")
                        .IsRequired()
                        .HasConstraintName("FK__TrialInve__Trial__5165187F");

                    b.Navigation("Investigator");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialSite", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", "Trial")
                        .WithMany("TrialSites")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Trials", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.TrialType", "TrialsType")
                        .WithMany("Trials")
                        .HasForeignKey("TrialTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Trial_TrialType");

                    b.Navigation("TrialsType");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Visit", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Participants", "Participant")
                        .WithMany("Visits")
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("FK_Participant_Id");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("TrialSite", b =>
                {
                    b.HasOne("PharmaClinicalSuite.Domain.Models.Sites", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__TrialSite__SiteI__5812160E");

                    b.HasOne("PharmaClinicalSuite.Domain.Models.Trials", null)
                        .WithMany()
                        .HasForeignKey("TrialId")
                        .IsRequired()
                        .HasConstraintName("FK__TrialSite__Trial__571DF1D5");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+CaseReportform", b =>
                {
                    b.Navigation("DataCollectionFields");

                    b.Navigation("ParticipantFormEntries");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+DataCollectionFields", b =>
                {
                    b.Navigation("ParticipantFieldData");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Data_Collection+ParticipantFormEntries", b =>
                {
                    b.Navigation("ParticipantFieldData");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Investigator", b =>
                {
                    b.Navigation("TrialsInvestigators");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Participants", b =>
                {
                    b.Navigation("AdverseEvents");

                    b.Navigation("Enrollments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.TrialType", b =>
                {
                    b.Navigation("Trials");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.Trials", b =>
                {
                    b.Navigation("AdverseEvents");

                    b.Navigation("CaseReportForms");

                    b.Navigation("Enrollments");

                    b.Navigation("TrialSites");

                    b.Navigation("TrialsInvestigators");
                });

            modelBuilder.Entity("PharmaClinicalSuite.Domain.Models.WithdrawalReason", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
